def p_1():
    print("1", end="")
def p_2():
    print("2", end="")
def p_3():
    print("3", end="")
def p_4():
    print("4", end="")
def p_5():
    print("5", end="")
def p_6():
    print("6", end="")
def p_7():
    print("7", end="")
def p_8():
    print("8", end="")
def p_9():
    print("9", end="")
def p_0():
    print("0", end="")
p_8(), p_8(), p_0(), p_0(), p_5(), p_5(), p_5(), p_3(), p_5(), p_3(), p_5() 